### ISSUE TITLE
Wi-fi kartı

### ISSUE THREAD

**Issue by Mystophos00** [omer-dogan/whoami#12]
Kali için yeni Wi-fi kartı aldım ancak whoami programı mac adreslerini değiştirme safhasında tıkanıyor ve ilerlemiyor sorunu nasıl çözebilirim

**Comment by omer-dogan** [comment]
Sanal makine kullanıyorsanız ağ kartınızı takmanıza gerek yok ancak yinede kullanmak istiyorsanız sorun hakkında biraz daha detay vermeniz gerek yaşadığınız sorun bir çok nedenden olabilir.

**Comment by Mystophos00** [comment]
Evet sanal makine kullanıyorum ağ kartını takmadan önce böyle bir sorun yaşamıyordum bu gün ilk defa denedim ve böyle bir sorun yaşıyorum %65 safhasında çıktıda mac adreslerinin değiştirildiğini yazarken tıkanıyor program.

**Comment by omer-dogan** [comment]
Son sürüm kullandığınıza emin misiniz? Bu tür sorunlar v1.4.1 de fixlendi. %65 olarak görüyorsanız zaten o sadece bir önceki sürümde öyleydi.

**Comment by Mystophos00** [comment]
Güncelleyince sorun kalmadı teşekkür ederim :)
